### PR TITLE
New function permit execute action on other APIs (CP 1, CP 2 and UAPI)

### PR DESCRIPTION
**Pull request by munikes**
The function is similar than cpanel function, I only add a new parameter with the API ID and I handler of some new errors.
Sorry for my English., :).

### CODE REVIEW

**Comment by munikes** [comment]
Sorry I fixed the return data.

**Comment by mgufrone** [comment]
nice patch! would you mind to update the readme file too? it would be helpful.

**Comment by munikes** [comment]
Ok, I try but my English is poor.

**Comment by munikes** [comment]
Hi, I try to document the function. And add a return result.

**Comment by mgufrone** [comment]
Thank you @munikes :+1:

**Comment by munikes** [comment]
thank you too. :+1:

**Comment by munikes** [comment]
@mgufrone I don't know but is it necessary to update the packagist to a new version?, because when I want to use the composer to install new changes of the package and I put "gufy/cpanel-php":"~1.0" the package don't change, only change when I put "gufy/cpanel-php":"dev-master". 
Thank you, and sorry for the inconvenience.

**Comment by mgufrone** [comment]
i forgot to bump the version up. will do it later.

**Pull request merged**
